image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint-and-test:
  stage: test
  script:
    - npm run install
    - npm install --save-dev esbuild
    - npm run test
    - npm run lint
    - npm run build-all

# Deploy docs to Gitlab pages
pages:
  stage: deploy
  only:
    - master
  script:
    - npm run install
    - npm run docs
    - mv docs public
  artifacts:
    paths:
      - public
